name: death_by_cycle
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - geopandas
  - patsy
  - statsmodels
  - jupyterlab
  - notebook
  - pip
  - pip:
    - addict==2.4.0
    - yacs
