name: death_by_cycle
channels:
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - geopandas
  - jupyterlab
  - notebook
  - pip
  - pip:
    - addict==2.4.0
    - yacs
